version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-db
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_START_RPC: "true"
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra-init:/docker-entrypoint-initdb.d
