version: "3.8"

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-db
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_START_RPC: "true"
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra-init:/docker-entrypoint-initdb.d

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - ./scripts-init:/scripts-init
    command:
      [
        "sh",
        "-c",
        "chmod +x /scripts-init/kafka-init.sh && /scripts-init/kafka-init.sh && /etc/confluent/docker/run",
      ]
